dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional
  - sudo pip install sphinx
env:
  global: # The following are for the dockerhub DOCKER_USER and DOCKER_PASS env vars used in the push script
    - secure: "asTBef+rKlsmMAJkU01a/pyQjn4yyatr/HGJpMYHJF1E4bEOoJMBm2bMLO1lbGOQKWWdbSCaAL8edl/K7W9+9cWVzwLEuXHOOHFeqHexDiWlJ5+IsrDrUDgvjYdMuzXdZna3bYVFCZSgbfgzvdM61iu18CTaq33TSL2lwZm8RnM="
    - secure: "EANyMcoEcWUNSPCXACXtBU7eE5WPvJcjNk+hJ1Cdr1MYO5zv7y2iJQLyKIs13J1KfUttzZLsRG4VZBFptNuCW7OANzl/vgWtTuwEGMwWmOY329i0Yt9jCtZbZF2/2oF2htnVAtimK5DHCoOSuII9HHy3QmN4wJZT58pE8DNPy+M="
install:
  - cd ..
  - git clone https://github.com/kbase/jars
  - cd -

script:
  - ant javadoc
  - ant compile
  - docker pull kbase/kb_jre
  - make docker_image

after_success:
  - IMAGE_NAME=kbase/kb_ujs ./build/push2dockerhub.sh

